apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  type: NodePort
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gateway
  name: gateway
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - env:
        - name: KAFKA_BROKER
          value: kafka-service-1:9092,kafka-service-2:9092,kafka-service-3:9092
        image: gateway:0.1
        imagePullPolicy: ""
        name: gateway
        ports:
        - containerPort: 8080
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: micr-handler
  name: micro-handler
spec:
  replicas: 3
  selector:
    matchLabels:
      app: micro-handler
  template:
    metadata:
      labels:
        app: micro-handler
    spec:
      containers:
      - env:
        - name: KAFKA_BROKER
          value: kafka-service-1:9092,kafka-service-2:9092,kafka-service-3:9092
        image: micro-handler:0.1
        imagePullPolicy: ""
        name: gateway
      restartPolicy: Always
