apiVersion: v1
kind: Service
metadata:
  name: zoo-service
spec:
  ports:
    - name: client
      port: 2181
      targetPort: 2181
    - name: follower
      port: 2888
      targetPort: 2888
    - name: leader
      port: 3888
      targetPort: 3888
  selector:
    app: zoo
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: zoo
  name: zoo
spec:
  selector:
      matchLabels:
        app: zoo
  template:
    metadata:
      labels:
        app: zoo
    spec:
      hostname: zoo-service
      containers:
        - name: zoo
          image: wurstmeister/zookeeper
          env:
            #- name: ZOOKEEPER_ID
            #value: "1"
            #- name: ZOOKEEPER_SERVER_1
            #value: zoo-srv
          ports:
            - containerPort: 2181
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service-1
spec:
  ports:
    - port: 9092
      targetPort: 9092
      name: "9092"
  selector:
    app: kafka-broker-1
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: kafka-broker-1
  name: kafka-broker-1
spec:
  replicas: 1
  selector:
      matchLabels:
        app: kafka-broker-1
  template:
    metadata:
      labels:
        app: kafka-broker-1
    spec:
      hostname: kafka-service-1
      containers:
        - name: kafka-broker-1
          image: wurstmeister/kafka
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ADVERTISED_PORT
              value: "9092"
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: kafka-service-1
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://0.0.0.0:9092
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zoo-service:2181
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_CREATE_TOPICS
              value: request:3:3,response:3:3
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service-2
spec:
  ports:
    - port: 9092
      targetPort: 9092
      name: "9092"
  selector:
    app: kafka-broker-2
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: kafka-broker-2
  name: kafka-broker-2
spec:
  replicas: 1
  selector:
      matchLabels:
        app: kafka-broker-2
  template:
    metadata:
      labels:
        app: kafka-broker-2
    spec:
      hostname: kafka-service-2
      containers:
        - name: kafka-broker-2
          image: wurstmeister/kafka
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ADVERTISED_PORT
              value: "9092"
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: kafka-service-2
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://0.0.0.0:9092
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zoo-service:2181
            - name: KAFKA_BROKER_ID
              value: "2"
            - name: KAFKA_CREATE_TOPICS
              value: request:3:3,response:3:3
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service-3
spec:
  ports:
    - port: 9092
      targetPort: 9092
      name: "9092"
  selector:
    app: kafka-broker-3
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: kafka-broker-3
  name: kafka-broker-3
spec:
  replicas: 1
  selector:
      matchLabels:
        app: kafka-broker-3
  template:
    metadata:
      labels:
        app: kafka-broker-3
    spec:
      hostname: kafka-service-3
      containers:
        - name: kafka-broker-3
          image: wurstmeister/kafka
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ADVERTISED_PORT
              value: "9092"
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: kafka-service-3
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://0.0.0.0:9092
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zoo-service:2181
            - name: KAFKA_BROKER_ID
              value: "3"
            - name: KAFKA_CREATE_TOPICS
              value: request:3:3,response:3:3
